name: build

on:
  workflow_dispatch:
    inputs:
      COMPILER:
        description: 'Compiler to use'
        required: true
        default: 'Neutron-Clang'
      KSU:
        description: 'Root: ksu (for KernelSU), both (KSU+SuSFS), or none'
        required: false
        default: 'ksu'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40

    steps:
      - name: Checkout Builder
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          dnf group install development-tools -y
          dnf install llvm lld bc bison ca-certificates curl flex glibc-devel.i686 glibc-devel binutils-devel openssl python3 python2 zstd clang gcc-arm-linux-gnu dtc libxml2 libarchive openssl-devel perl tomsfastmath-devel wget xz which git -y
          ln -sf "/usr/bin/python3" /usr/bin/python
          git config --global user.name "zclkkk"
          git config --global user.email "zclkkk@example.com"

      - name: Clone Kernel Source and Patch WireGuard
        run: |
          git clone --depth=1 --quiet https://github.com/SreNiyt/kernel kernel
          
          # Generate the WireGuard source patch and apply it straight to the kernel tree
          ./wireguard-linux-compat/kernel-tree-scripts/create-patch.sh | patch -p1 -d kernel

          # Enable WireGuard in the defconfig dynamically
          # NOTE: Change 'vendor/your_device_defconfig' to your actual defconfig path!
          echo "CONFIG_WIREGUARD=y" >> kernel/arch/arm64/configs/blossom_defconfig
          echo "CONFIG_WIREGUARD_DEBUG=n" >> kernel/arch/arm64/configs/blossom_defconfig

      - name: Compile Kernel
        run: |
          cd kernel
          # We skip the tg_utils calls
          if [ "${{ github.event.inputs.KSU }}" = "ksu" ] || [ "${{ github.event.inputs.KSU }}" = "both" ]; then
            bash ../ksu/applyPatches.sh
          fi
          bash ../build.sh "${{ github.event.inputs.COMPILER }}"

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: Sashimi-Dandelion-Headless
          path: kernel/*.zip
          retention-days: 5

