name: Dandelion Headless Build

on:
  workflow_dispatch:
    inputs:
      COMPILER:
        description: 'Compiler to use'
        required: true
        default: 'AOSP-Clang'
      KSU:
        description: 'Root: ksu (for KernelSU), both (KSU+SuSFS), or none'
        required: false
        default: 'none'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:40

    steps:
      - name: Checkout Builder
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          dnf group install development-tools -y
          dnf install llvm lld bc bison ca-certificates curl flex glibc-devel.i686 glibc-devel binutils-devel openssl python3 python2 zstd clang gcc-arm-linux-gnu dtc libxml2 libarchive openssl-devel perl tomsfastmath-devel wget xz which git -y
          ln -sf "/usr/bin/python3" /usr/bin/python
          git config --global user.name "zclkkk"
          git config --global user.email "zclkkk@example.com"
          
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/zyexro/sashimi_kernel_xiaomi_blossom -b sashimi kernel

      - name: broken screen patch
        run: |
          cd kernel
          
          # 1. Aggressive Undervolt (-35mV)
          sed -i 's/opp-microvolt = <1118750>;/opp-microvolt = <1083750>;/g' arch/arm64/boot/dts/mediatek/mt6765.dts
          
          # 2. Performance Response
          sed -i 's/CONFIG_HZ_100=y/CONFIG_HZ_300=y/' arch/arm64/configs/blossom_defconfig
          sed -i 's/CONFIG_HZ=100/CONFIG_HZ=300/' arch/arm64/configs/blossom_defconfig
          sed -i 's/CONFIG_PREEMPT_VOLUNTARY=y/CONFIG_PREEMPT=y/' arch/arm64/configs/blossom_defconfig
          
          
      - name: Compile Kernel
        run: |
          cd kernel
          # We skip the tg_utils calls since you don't use Telegram
          if [ "${{ github.event.inputs.KSU }}" = "ksu" ] || [ "${{ github.event.inputs.KSU }}" = "both" ]; then
            bash ../ksu/applyPatches.sh
          fi
          bash ../build.sh "${{ github.event.inputs.COMPILER }}"

      - name: Upload Flashable Zip
        uses: actions/upload-artifact@v4
        with:
          name: Sashimi-Dandelion-Headless
          path: kernel/*.zip
          retention-days: 5

